builds:
  - ldflags:
      - -w -s
      - -X github.com/mudler/containerbay/internal.Version={{.Tag}}
      - -X github.com/mudler/containerbay/internal.Commit={{.Commit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - 386
      - arm64
source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Tag }}-source'
archives:
  # Default template uses underscores instead of -
  - name_template: "{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: '{{ .ProjectName }}-{{ .Tag }}-checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request'